AztpaFactory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.i18n import JavaScriptCatalog, set_language
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^dashboard/', include(('dashboard.urls','dashboard'), namespace='dashboard')),
    url(r'^account/',include(('account.urls','account'),namespace='account')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^products/',include('product.urls', namespace='product')),
    url(r'^page/',include(('page.urls','page'), namespace='page')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('core.urls',namespace='home')),
] + static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'core'
urlpatterns = [
    url(r'^$', views.home, name='home')
]

dashboard/product/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^types/$', views.product_type_list, name='product-type-list'),
    url(r'^types/add/$', views.product_type_create, name='product-type-add'),
    url(r'^types/(?P<pk>[0-9]+)/update/$', views.product_type_edit, name='product-type-update'),
    url(r'^types/(?P<pk>[0-9]+)/delete/$', views.product_type_delete, name='product-type-delete'),

    url(r'attributes/$', views.attribute_list, name='attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$', views.attribute_details, name='attribute-details'),
    url(r'attributes/add/$', views.attribute_create, name='attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/update/$', views.attribute_edit, name='attribute-update'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$', views.attribute_delete, name='attribute-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/add/$', views.attribute_value_create, name='attribute-value-add'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$', views.attribute_value_edit,name='attribute-value-update'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$',views.attribute_value_delete,name='attribute-value-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/values/reorder/$', views.ajax_reorder_attribute_values,name='attribute-values-reorder'),

    url(r'^$', views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/$', views.product_details, name='product-details'),
    url(r'^(?P<pk>[0-9]+)/publish/$', views.product_toggle_is_published, name='product-publish'),
    url(r'^add/select-type/$',views.product_select_type, name='product-add-select-type'),
    url(r'^add/(?P<type_pk>[0-9]+)/$',views.product_create, name='product-add'),
    url(r'^(?P<pk>[0-9]+)/update/$',views.product_edit, name='product-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$',views.product_delete, name='product-delete'),
    url(r'^bulk-update/$',views.product_bulk_update, name='product-bulk-update'),
    url(r'^ajax/products/$',views.ajax_products_list, name='ajax-products'),

    url(r'^(?P<product_pk>[0-9]+)/images/$', views.product_images, name='product-image-list'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',views.product_image_create, name='product-image-add'),
]

dashboard/urls.py
from django.urls import path, include
from django.conf.urls import url
from .settings.urls import urlpatterns as settings_urls
from .menu.urls import urlpatterns as menu_urls
from .staff.urls import urlpatterns as staff_urls
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^settings/', include(settings_urls)),
    url(r'^menu/', include(menu_urls)),
    url(r'^staff/', include(staff_urls)),
]

product/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'core'
urlpatterns = [
    url(r'^category/(?P<slug>[a-z0-9-_]+?)-(?P<category_id>[0-9]+)/$',views.category_index, name='category'),
    url(r'^details/(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/$',views.details, name='details'),
]

dashboard/category/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from core.utils import get_paginator_items
from product.models import Category
from ..menu.utils import get_menus_that_needs_update, update_menus
from ..views import staff_member_required
from .forms import CategoryForm


@staff_member_required
@permission_required('product.manage_products')
def category_list(request):
    categories = Category.tree.root_nodes().order_by('name')

    ctx = {
        'categories': categories,}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
@permission_required('product.manage_products')
def category_create(request, root_pk=None):
    path = None
    category = Category()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(
        request.POST or None, request.FILES or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-details', pk=root_pk)
        return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form, 'path': path}
    return TemplateResponse(request, 'dashboard/category/form.html', ctx)


@staff_member_required
@permission_required('product.manage_products')
def category_edit(request, root_pk=None):
    path = None
    category = get_object_or_404(Category, pk=root_pk)
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(
        request.POST or None, request.FILES or None, instance=category,
        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Updated category %s') % category)
        if root_pk:
            return redirect('dashboard:category-details', pk=root_pk)
        return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status, 'path': path}
    template = 'dashboard/category/form.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required('product.manage_products')
def category_details(request, pk):
    root = get_object_or_404(Category, pk=pk)
    path = root.get_ancestors(include_self=True) if root else []
    categories = root.get_children().order_by('name')
    ctx = {'categories': categories, 'path': path, 'root': root,}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
@permission_required('product.manage_products')
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        descendants = category.get_descendants()
        menus = get_menus_that_needs_update(categories=descendants)
        category.delete()
        if menus:
            update_menus(menus)
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Removed category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-details', kwargs={'pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-details', pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(
        request, 'dashboard/category/modal/confirm_delete.html', ctx)

dashboard/menu/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.decorators import permission_required
from ..views import staff_member_required
from django.contrib.sites.shortcuts import get_current_site
from django.template.response import TemplateResponse
from menu.models import Menu, MenuItem
from core.utils import get_paginator_items
from dashboard.menu.utils import get_menu_obj_text, update_menu
from django.contrib import messages
from django.utils.translation import pgettext_lazy
from django.http import JsonResponse
from django.db.models import Q
from django.urls import reverse
from .forms import AssignMenuForm, MenuForm, MenuItemForm

from page.models import Page
from menu.models import Category

# Create your views here.

@staff_member_required
@permission_required('core.manage_settings')
def index(request):
    menus = Menu.objects.all()
    menus = get_paginator_items(menus,request.GET.get('page'))
    site_settings = get_current_site(request).settings
    assign_menu_form = AssignMenuForm(request.POST or None,instance=site_settings)
    if request.POST and assign_menu_form.is_valid():
        assign_menu_form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Updated storefront menus')
        messages.success(request, msg)
        return redirect('dashboard:menu-index')
    ctx = {
        'menus' : menus,
        'assign_menu_form' : assign_menu_form,
        'site_settings' : site_settings,
    }
    return TemplateResponse(request, 'dashboard/menu/index.html', ctx)\



@staff_member_required
@permission_required('core.manage_settings')
def menu_details(request, pk):
    menu = get_object_or_404(Menu, pk=pk)
    menu_items = menu.items.filter(parent=None).prefetch_related(
        'category', 'page')

    ctx = {
        'menu': menu,
        'menu_items': menu_items,
    }
    return TemplateResponse(request, 'dashboard/menu/details.html', ctx)\


@staff_member_required
@permission_required('core.manage_settings')
def menu_item_details (request, menu_pk, item_pk):
    menu = get_object_or_404(Menu, pk=menu_pk)
    menu_item = menu.items.get(pk=item_pk)

    menu_items = menu_item.get_children().order_by('sort_order')

    ctx = {
        'menu': menu,
        'menu_items': menu_items,
        'menu_item': menu_item,
    }
    return TemplateResponse(request, 'dashboard/menu/item/details.html', ctx)


@staff_member_required
@permission_required('core.manage_settings')
def menu_create (request):
    menu = Menu()
    menu_form = MenuForm(request.POST, instance=menu)
    if menu_form.is_valid() and menu_form.has_changed() and request.POST:
        menu = menu_form.save()
        msg = pgettext_lazy('Dashboard message', 'Added menu %s') % (menu,)
        messages.success(request, msg)
        return redirect('dashboard:menu-index')
    ctx = {
        'form': menu_form,
        'menu': menu
    }
    return TemplateResponse(request, 'dashboard/menu/form.html', ctx)



@staff_member_required
@permission_required('menu.manage_menus')
def menu_edit(request, pk):
    menu = get_object_or_404(Menu, pk=pk)
    menu_form = MenuForm(request.POST or None, instance=menu)
    if menu_form.is_valid() and menu_form.has_changed() and request.POST:
        menu = menu_form.save()
        msg = pgettext_lazy('Dashboard message', 'Updated menu %s') % (menu,)
        messages.success(request, msg)
        return redirect('dashboard:menu-details', pk=menu.pk)
    ctx = {
        'form': menu_form,
        'menu': menu
    }

    return TemplateResponse(request, 'dashboard/menu/form.html', ctx)



@staff_member_required
@permission_required('menu.manage_menus')
def menu_delete(request, pk):
    menu = get_object_or_404(Menu, pk=pk)
    if request.method == 'POST':
        menu.delete()
        msg = pgettext_lazy('Dashboard message', 'Removed menu %s') % (menu,)
        messages.success(request, msg)
        return redirect('dashboard:menu-list')
    ctx = {
        'menu': menu, 'descendants': list(menu.items.all())}
    return TemplateResponse(
        request, 'dashboard/menu/modal/confirm_delete.html', ctx)



@staff_member_required
@permission_required('menu.manage_menus')
def ajax_menu_links(request):

    def get_obj_repr(obj):
        obj_id = str(obj.pk) + '_' + obj.__class__.__name__
        return {
            'id': obj_id,
            'text': get_menu_obj_text(obj)}

    def get_group_repr(model, label, filter_fields, query):
        queryset = model.objects.all()
        if search_query and search_query.lower() not in label.lower():
            kwargs = {
                '%s__contains' % (field,): query for field in filter_fields}
            queryset = queryset.filter(Q(**kwargs))
        return {
            'text': label,
            'children': [get_obj_repr(obj) for obj in queryset]}

    search_query = request.GET.get('q', '')
    groups = [
        get_group_repr(
            Category,
            pgettext_lazy('Link object type group description', 'Category'),
            ('name',),
            search_query),
        get_group_repr(
            Page,
            pgettext_lazy('Link object type group description', 'Page'),
            ('title',),
            search_query)
    ]

    groups = [group for group in groups if len(group.get('children')) > 0]
    return JsonResponse({'results': groups})



@staff_member_required
@permission_required('menu.manage_menus')
def menu_item_create(request, menu_pk, root_pk=None):
    menu = get_object_or_404(Menu, pk=menu_pk)
    path = None
    if root_pk:
        root = get_object_or_404(MenuItem, pk=root_pk)
        path = root.get_ancestors(include_self=True)
        menu_item = MenuItem(menu=menu, parent=root)
    else:
        menu_item = MenuItem(menu=menu)
    form = MenuItemForm(request.POST or None, instance=menu_item)
    if form.is_valid():
        menu_item = form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added menu item %s') % (menu_item,)
        messages.success(request, msg)
        update_menu(menu)
        if root_pk:
            return redirect(
                'dashboard:menu-item-details',
                menu_pk=menu.pk, item_pk=root_pk)
        return redirect('dashboard:menu-details', pk=menu.pk)
    ctx = {
        'form': form, 'menu': menu, 'menu_item': menu_item, 'path': path}
    return TemplateResponse(request, 'dashboard/menu/item/form.html', ctx)

@staff_member_required
@permission_required('menu.manage_menus')
def menu_item_delete(request, menu_pk, item_pk):
    menu = get_object_or_404(Menu, pk=menu_pk)
    menu_item = get_object_or_404(menu.items.all(), pk=item_pk)
    if request.method == 'POST':
        menu_item.delete()
        update_menu(menu)
        msg = pgettext_lazy(
            'Dashboard message', 'Removed menu item %s') % (menu_item,)
        messages.success(request, msg)
        root_pk = menu_item.parent.pk if menu_item.parent else None
        if root_pk:
            redirect_url = reverse(
                'dashboard:menu-item-details', kwargs={
                    'menu_pk': menu_item.menu.pk, 'item_pk': root_pk})
        else:
            redirect_url = reverse(
                'dashboard:menu-details', kwargs={'pk': menu.pk})
        return (
            JsonResponse({'redirectUrl': redirect_url}) if request.is_ajax()
            else redirect(redirect_url))
    ctx = {
        'menu_item': menu_item,
        'descendants': list(menu_item.get_descendants())}
    return TemplateResponse(
        request, 'dashboard/menu/item/modal/confirm_delete.html', ctx)



@staff_member_required
@permission_required('menu.manage_menus')
def menu_item_edit(request, menu_pk, item_pk):
    menu = get_object_or_404(Menu, pk=menu_pk)
    menu_item = get_object_or_404(menu.items.all(), pk=item_pk)
    path = menu_item.get_ancestors(include_self=True)
    form = MenuItemForm(request.POST or None, instance=menu_item)
    if form.is_valid():
        menu_item = form.save()
        update_menu(menu)
        msg = pgettext_lazy(
            'Dashboard message', 'Saved menu item %s') % (menu_item,)
        messages.success(request, msg)
        return redirect(
            'dashboard:menu-item-details', menu_pk=menu.pk, item_pk=item_pk)
    ctx = {
        'form': form, 'menu': menu, 'menu_item': menu_item, 'path': path}
    return TemplateResponse(request, 'dashboard/menu/item/form.html', ctx)

dashboard/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import (staff_member_required as _staff_member_required, user_passes_test)

# Create your views here.

def staff_member_required(f):
    return _staff_member_required(f,login_url='account:login')

@staff_member_required
def index(request):
    return render(request,'dashboard/index.html')

dashboard/templates/dashboard/product/product_type/form.html
{% extends "dashboard/index.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}
  {% if product_type.pk %}
    {{ product_type }}
  {% else %}
    {% trans "Add new product type" context "Product type page title" %}
  {% endif %}
  - {% trans "Products" context "Dashboard products list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-products{% endblock %}

{% block menu_product_types_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:product-type-list" as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:product-type-list" %}" class="breadcrumb">
        {% trans "Product types" context "Dashboard product types list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:product-type-list" %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% if product_type.pk %}
          {{ product_type }}
        {% else %}
          {% trans 'Add new product type' context "Product type breadcrumbs" %}
        {% endif %}
      </span>
    </li>
  </ul>
{% endblock %}

{% block header_extra %}
  {% if product_type.pk %}
    <a class="dropdown-button right" href="#" data-activates="context-menu" data-constrainwidth="false">
      <svg data-src="{% static "dashboard/images/more-vert.svg" %}" height="24" width="24" />
    </a>
    <ul id="context-menu" class="dropdown-content">
      {% if perms.product.manage_products %}
      <li>
        <a href="#base-modal" data-href="{% url 'dashboard:product-type-delete' pk=product_type.pk %}" class="modal-trigger-custom">
          {% trans "Remove product type" context "Product type action" %}
        </a>
      </li>
      {% endif %}
    </ul>
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l9">
      <div class="card">
        <form method="post" id="form-product" enctype="multipart/form-data" novalidate>
          <div class="card-content card-content-form">
            {% csrf_token %}
            <div class="row">
              {{ form.name|materializecss }}
            </div>
            <div class="row">
              <div class="col s12 m8">
                <div class="row">
                  {{ form.product_attributes|materializecss:"input-field s12" }}
                </div>
              </div>

            </div>
          </div>
          {% if perms.product.manage_products %}
          <div class="card-action right-align">
            <a href="{% url 'dashboard:product-type-list' %}" class="btn-flat waves-effect">
              {% trans "Cancel" context "Dashboard cancel action" %}
            </a>
            {% if product_type.pk %}
              <button type="submit" class="btn waves-effect">
                {% trans "Update" context "Dashboard update action" %}
              </button>
            {% else %}
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
          {% endif %}
        </form>
      </div>
    </div>
    <div class="col m12 l3 help-box">
      <p class="grey-text">
        <svg data-src="{% static "dashboard/images/help.svg" %}" width="18" height="18" />
        {% blocktrans trimmed context "Product type help text" %}
        Product Type is a template used for creating new products.
        It also controls which attributes can be used during product creation process.
        {% endblocktrans %}
      </p>
    </div>
  </div>
{% endblock %}

dashboard/templates/dashboard/product/product_type/list.html
{% extends "dashboard/index.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}
{% load utils %}

{% block title %}
  {% trans "Product types" context "Dashboard product types list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-products{% endblock %}

{% block menu_product_types_class %}active{% endblock %}

{% block header_extra %}
  {% if perms.product.manage_products %}
  <div class="btn-fab-fixed">
    <a class="btn-fab-default waves-effect waves-light" title="{% trans "Add product type" context "Product type list add button text" %}" href="{% url 'dashboard:product-type-add' %}">
      <svg data-src="{% static "dashboard/images/add.svg" %}" />
    </a>
  </div>
  {% endif %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
      {% trans "Product types" context "Dashboard product types list" %}
    </li>
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      {% if product_types %}
        <div class="card">
          <div class="data-table-container">
            <table class="bordered highlight data-table data-table-description">
              <thead>
                <tr>
                  {% trans "Name" context "Dashboard product types list table header name" as label %}
                  {% sorting_header 'name' label %}

                  <th>
                    {% trans "Product attributes" context "Product type item list text" %}
                  </th>
                </tr>
              </thead>
              <tbody>
              {% for pk, name, product_attributes in product_types %}
                <tr data-action-go="{% if perms.product.manage_products %}{% url 'dashboard:product-type-update' pk=pk %}{% endif %}">
                  <td>
                    {{ name }}
                  </td>
                  <td>
                    {% if product_attributes %}
                      {{ product_attributes|join:", " }}
                    {% else %}
                      -
                    {% endif %}
                  </td>

                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      {% else %}
        {% if is_empty %}
          {% include 'dashboard/product/product_type/zero_page.html' %}
        {% else %}
          <div class="col s12">
            <div class="not-found">
              <p class="grey-text">
                {% trans "No product types found." context "Empty product type list message" %}
              </p>
            </div>
          </div>
        {% endif %}
      {% endif %}
    </div>
    <div class="col s12 l3" id="filters">
    </div>
  </div>
{% endblock %}

dashboard/templates/dashboard/product/product_type/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "No product types found." %}{% endblock %}
{% block content %}
  {% static "dashboard/images/add.svg" as img_path %}
  {% blocktrans %}
    Product types are templates used to create new products. They allow assigning custom attributes to the products of the same type.<br>
    You can add product types by using the <span class="btn-fab-presentation"><svg data-src="{{ img_path }}" /></span> button.
  {% endblocktrans %}
{% endblock %}