AztpaFactory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.i18n import JavaScriptCatalog, set_language
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^dashboard/', include(('dashboard.urls','dashboard'), namespace='dashboard')),
    url(r'^account/',include(('account.urls','account'),namespace='account')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^products/',include('product.urls', namespace='product')),
    url(r'^page/',include(('page.urls','page'), namespace='page')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('core.urls',namespace='home')),
] + static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

account/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.login, name='login' ),
    url(r'^logout/$', views.logout, name='logout' ),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'core'
urlpatterns = [
    url(r'^$', views.home, name='home')
]

dashboard/urls.py
from django.urls import path, include
from django.conf.urls import url
from .settings.urls import urlpatterns as settings_urls
from .menu.urls import urlpatterns as menu_urls
from .staff.urls import urlpatterns as staff_urls
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^settings/', include(settings_urls)),
    url(r'^menu/', include(menu_urls)),
    url(r'^staff/', include(staff_urls)),
]

core/models.py
from django.contrib.sites.models import Site
from django.db import models
from django.utils.translation import pgettext_lazy
from django.db.models import F, Max
from . import AuthenticationBackends


class SiteSettings(models.Model):
    slug = models.SlugField(unique=True)
    site = models.OneToOneField(Site, related_name='settings', on_delete=models.CASCADE)
    header_text = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=500, blank=True)
    top_menu = models.ForeignKey('menu.Menu', on_delete=models.SET_NULL, verbose_name=pgettext_lazy('Top menu', 'Top menu field'), related_name='+', blank=True,null=True)
    bottom_menu = models.ForeignKey('menu.Menu', on_delete=models.SET_NULL, verbose_name=pgettext_lazy('Bottom menu', 'Bottom menu field'), related_name='+', blank=True,null=True)
    #include_taxes_in_prices = models.BooleanField(default=True)
    #display_gross_prices = models.BooleanField(default=True)
    #charge_taxes_on_shipping = models.BooleanField(default=True)
    #track_inventory_by_default = models.BooleanField(default=True)
    #homepage_collection = models.ForeignKey('product.Collection', on_delete=models.SET_NULL, related_name='+',blank=True, null=True)
    #default_weight_unit = models.CharField(max_length=10, choices=WeightUnits.CHOICES,default=WeightUnits.KILOGRAM)

    class Meta:
        permissions = ((
            'manage_settings', pgettext_lazy(
                'Permission description', 'Manage settings.')),)

    def __str__(self):
        return self.site.name

    def available_backends(self):
        return self.authorizationkey_set.values_list('name', flat=True)


class AuthorizationKey(models.Model):
    site_settings = models.ForeignKey(SiteSettings, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, choices=AuthenticationBackends.BACKENDS)
    key = models.TextField()
    password = models.TextField()

    class Meta:
        unique_together = (('site_settings', 'name'),)

    def __str__(self):
        return self.name

    def key_and_secret(self):
        return self.key, self.password



class SortableModel(models.Model):
    sort_order = models.PositiveIntegerField(editable=False, db_index=True)

    class Meta:
        abstract = True

    def get_ordering_queryset(self):
        raise NotImplementedError('Unknown ordering queryset')

    def save(self, *args, **kwargs):
        if self.sort_order is None:
            qs = self.get_ordering_queryset()
            existing_max = qs.aggregate(Max('sort_order'))
            existing_max = existing_max.get('sort_order__max')
            self.sort_order = 0 if existing_max is None else existing_max + 1
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        qs = self.get_ordering_queryset()
        qs.filter(sort_order__gt=self.sort_order).update(
            sort_order=F('sort_order') - 1)
        super().delete(*args, **kwargs)

core/views.py
from django.shortcuts import render
from django.template.response import TemplateResponse

# Create your views here.


def home(request):
    return render(request,'core/home.html')

core/templates/core/base.html
<!DOCTYPE html>
{% load i18n %}
{% load placeholder %}
{% load static %}
{% load translate %}

<html lang="{{ LANGUAGE_CODE }}" class="no-js">
<head>
    <title>{% block title %}{{ site.name }}{% endblock %}</title>
    {% block meta %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="generator" content="Saleor">
        <meta name="theme-color" content="#333333">
        <meta name="msapplication-TileColor" content="#2b5797">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="{{ site.name }}">
        <meta name="og:type" content="website">
        {% get_available_languages as LANGUAGES %}
        {% for lang_code, language_name in LANGUAGES %}
            <link rel="alternate" hreflang="{{ lang_code }}"
                  href="{% translate_url url=request.path lang_code=lang_code %}"/>
        {% endfor %}
    {% endblock meta %}

    {% include 'core/favicon.html' %}

    {% block stylesheet %}{% endblock stylesheet %}

    {% block meta_tags %}
        <meta property="og:title" content="{{ site.settings.translated.header_text }}">
        <meta property="og:description" content="{{ site.settings.translated.description }}">
        <meta name="description" content="{{ site.settings.translated.description }}">
        <meta property="og:url" content="{{ request.build_absolute_uri }}">
        <meta property="og:image" content="{% static "images/block1.png" %}">
    {% endblock meta_tags %}


    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>

{% block header %}
<header class="navbar" role="navigation">
    <div class="navbar__login container-fluid {% if user.is_impersonate %} bg-warning{% endif %}">
        <div class=" d-none d-md-block container">
            <div class="row">
                <div class="col-6">
                    <p class="text-left">{{ site.settings.translated.header_text }}</p>
                </div>
                <div class="col-6">
                    <ul class="float-right">
                        {% get_available_languages as LANGUAGES %}

                        {# We display language picker only if there're languages to pick from #}
                        {% if LANGUAGES|length > 1 %}
                            {% get_current_language as LANGUAGE_CODE %}
                            <li>
                                <div class="language-picker dropdown show">
                                    <a class="dropdown-toggle dropdown-link " id="language-picker-button">
                                        {{ LANGUAGE_CODE|language_name_local }}
                                    </a>
                                </div>
                            </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                            {% if user.is_staff or request.impersonator.is_staff %}
                                <li>
                                    <a href="{% url "dashboard:index" %}" target="_blank" rel="noopener">
                                        {% trans "Dashboard" context "Main navigation item" %}
                                    </a>
                                </li>
                            {% endif %}
                            <li>
                                <a href="{% url "account:logout" %}">
                                    {% trans "Log out" context "Main navigation item" %}</a>
                            </li>
                        {% else %}
                        <li>
                            <a rel="nofollow" href="{% url "account:login" %}">
                                {% trans "Log in" context "Main navigation item" %}
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar__menu container d-block">
        <nav class="navigation">
        </nav>
    </div>
</header>
{% endblock %}
<div class="container maincontent">
    {% block topcontent %}{% endblock topcontent %}
    {% block breadcrumb %}
    {% endblock breadcrumb %}
    {% block content %}
    {% endblock content %}
</div>
{% block footer %}
{% endblock %}
{% block footer_scripts %}
{% endblock footer_scripts %}
{% if LANGUAGES|length > 1 %}

{% endif %}
</body>
</html>

core/templates/core/favicon.html
{% load static %}

<meta name="application-name" content="{{ site.name }}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
<link rel="mask-icon" href="{% static 'favicons/safari-pinned-tab.svg' %}" color="#78818f">

core/templates/core/home.html
{% extends 'core/base.html' %}