AztpaFactory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.i18n import JavaScriptCatalog, set_language
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^dashboard/', include(('dashboard.urls','dashboard'), namespace='dashboard')),
    url(r'^account/',include(('account.urls','account'),namespace='account')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^products/',include('product.urls', namespace='product')),
    url(r'^page/',include(('page.urls','page'), namespace='page')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('core.urls',namespace='home')),
] + static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

account/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.login, name='login' ),
    url(r'^logout/$', views.logout, name='logout' ),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'core'
urlpatterns = [
    url(r'^$', views.home, name='home')
]

dashboard/menu/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='menu-index'),
    url(r'^add/$', views.menu_create, name='menu-add'),
    url(r'^(?P<pk>[0-9]+)/delete/$',views.menu_delete, name='menu-delete'),
    url(r'^(?P<pk>[\w-]+)/$', views.menu_details, name='menu-details'),
    url(r'^(?P<pk>[\w-]+)/edit/$', views.menu_edit, name='menu-edit'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/$',views.menu_item_details, name='menu-item-details'),
    url(r'^(?P<menu_pk>[0-9]+)/add/$', views.menu_item_create, name='menu-item-add'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/add/$', views.menu_item_create, name='menu-item-add'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/delete/$', views.menu_item_delete, name='menu-item-delete'),
    url(r'^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/edit/$', views.menu_item_edit, name='menu-item-edit'),
    url(r'^ajax/links/$',views.ajax_menu_links, name='ajax-menu-links'),
   # url(r'^(?P<slug>[\w-]+)/edit/$', views.settings_edit, name='settings-edit'),
]

dashboard/page/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.page_list, name='page-list'),
    url(r'^add/$', views.page_add, name='page-add'),
    url(r'^(?P<pk>[0-9]+)/$', views.page_details, name='page-details'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.page_update, name='page-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.page_delete, name='page-delete')
]

dashboard/product/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^types/$', views.product_type_list, name='product-type-list'),
    url(r'^types/add/$', views.product_type_create, name='product-type-add'),
    url(r'^types/(?P<pk>[0-9]+)/update/$', views.product_type_edit, name='product-type-update'),
    url(r'^types/(?P<pk>[0-9]+)/delete/$', views.product_type_delete, name='product-type-delete'),

    url(r'attributes/$', views.attribute_list, name='attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$', views.attribute_details, name='attribute-details'),
    url(r'attributes/add/$', views.attribute_create, name='attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/update/$', views.attribute_edit, name='attribute-update'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$', views.attribute_delete, name='attribute-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/add/$', views.attribute_value_create, name='attribute-value-add'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$', views.attribute_value_edit,name='attribute-value-update'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$',views.attribute_value_delete,name='attribute-value-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/values/reorder/$', views.ajax_reorder_attribute_values,name='attribute-values-reorder'),

    url(r'^$', views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/$', views.product_details, name='product-details'),
    url(r'^(?P<pk>[0-9]+)/publish/$', views.product_toggle_is_published, name='product-publish'),
    url(r'^add/select-type/$',views.product_select_type, name='product-add-select-type'),
    url(r'^add/(?P<type_pk>[0-9]+)/$',views.product_create, name='product-add'),
    url(r'^(?P<pk>[0-9]+)/update/$',views.product_edit, name='product-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$',views.product_delete, name='product-delete'),
    url(r'^bulk-update/$',views.product_bulk_update, name='product-bulk-update'),
    url(r'^ajax/products/$',views.ajax_products_list, name='ajax-products'),

    url(r'^(?P<product_pk>[0-9]+)/images/$', views.product_images, name='product-image-list'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',views.product_image_create, name='product-image-add'),
]

dashboard/staff/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='staff-index'),
    url(r'^staff-create/$', views.staff_create, name='staff-create'),
    url(r'^(?P<pk>[0-9]+)/$', views.staff_details, name='staff-details'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.staff_delete, name='staff-delete'),
    #url(r'^(?P<slug>[\w-]+)/$', views.settings_details, name='settings-details'),
   # url(r'^(?P<slug>[\w-]+)/edit/$', views.settings_edit, name='settings-edit'),
]

dashboard/urls.py
from django.urls import path, include
from django.conf.urls import url
from .settings.urls import urlpatterns as settings_urls
from .menu.urls import urlpatterns as menu_urls
from .staff.urls import urlpatterns as staff_urls
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^settings/', include(settings_urls)),
    url(r'^menu/', include(menu_urls)),
    url(r'^staff/', include(staff_urls)),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/category/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.utils.translation import pgettext_lazy

from product.models import Category
from ..seo.fields import SeoDescriptionField, SeoTitleField


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        exclude = ['slug']

        labels = {
            'name': pgettext_lazy('Item name', 'Name'),
            'description': pgettext_lazy('Description', 'Description'),
            'background_image': pgettext_lazy(
                'Category form',
                'Background Image')}


    def __init__(self, *args, **kwargs):
        self.parent_pk = kwargs.pop('parent_pk')
        super().__init__(*args, **kwargs)
        self.fields['seo_description'] = SeoDescriptionField(
            extra_attrs={'data-bind': self['description'].auto_id})
        self.fields['seo_title'] = SeoTitleField(
            extra_attrs={'data-bind': self['name'].auto_id})

    def save(self, commit=True):
        if self.parent_pk:
            self.instance.parent = get_object_or_404(
                Category, pk=self.parent_pk)
        return super().save(commit=commit)

dashboard/category/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from core.utils import get_paginator_items
from product.models import Category
from ..menu.utils import get_menus_that_needs_update, update_menus
from ..views import staff_member_required
from .forms import CategoryForm


@staff_member_required
@permission_required('product.manage_products')
def category_list(request):
    categories = Category.tree.root_nodes().order_by('name')

    ctx = {
        'categories': categories,}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
@permission_required('product.manage_products')
def category_create(request, root_pk=None):
    path = None
    category = Category()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(
        request.POST or None, request.FILES or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-details', pk=root_pk)
        return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form, 'path': path}
    return TemplateResponse(request, 'dashboard/category/form.html', ctx)


@staff_member_required
@permission_required('product.manage_products')
def category_edit(request, root_pk=None):
    path = None
    category = get_object_or_404(Category, pk=root_pk)
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(
        request.POST or None, request.FILES or None, instance=category,
        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Updated category %s') % category)
        if root_pk:
            return redirect('dashboard:category-details', pk=root_pk)
        return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status, 'path': path}
    template = 'dashboard/category/form.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required('product.manage_products')
def category_details(request, pk):
    root = get_object_or_404(Category, pk=pk)
    path = root.get_ancestors(include_self=True) if root else []
    categories = root.get_children().order_by('name')
    ctx = {'categories': categories, 'path': path, 'root': root,}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
@permission_required('product.manage_products')
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        descendants = category.get_descendants()
        menus = get_menus_that_needs_update(categories=descendants)
        category.delete()
        if menus:
            update_menus(menus)
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Removed category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-details', kwargs={'pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-details', pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(
        request, 'dashboard/category/modal/confirm_delete.html', ctx)

dashboard/page/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.decorators import permission_required
from ..views import staff_member_required
from django.contrib.sites.shortcuts import get_current_site
from django.template.response import TemplateResponse
from menu.models import Menu, MenuItem
from core.utils import get_paginator_items
from dashboard.menu.utils import update_menus, update_menu,get_menus_that_needs_update
from django.contrib import messages
from django.utils.translation import pgettext_lazy
from django.http import JsonResponse
from django.db.models import Q
from django.urls import reverse

from page.models import Page
from .forms import PageForm
from menu.models import Category


@staff_member_required
@permission_required('page.manage_pages')
def page_list(request):
    pages = Page.objects.all()

    ctx = {
        'pages': pages,
    }
    return TemplateResponse(request, 'dashboard/page/list.html', ctx)


@staff_member_required
@permission_required('page.manage_pages')
def page_add(request):
    page = Page()
    form = PageForm(request.POST or None, instance=page)
    if form.is_valid():
        form.save()
        msg = pgettext_lazy('Dashboard message', 'Saved page')
        messages.success(request, msg)
        return redirect('dashboard:page-details', pk=page.pk)
    ctx = {
        'page': page, 'form': form}
    return TemplateResponse(request, 'dashboard/page/form.html', ctx)


@staff_member_required
@permission_required('page.manage_pages')
def page_details(request, pk):
    page = get_object_or_404(Page, pk=pk)
    ctx = {
        'page': page,
    }
    return TemplateResponse(request, 'dashboard/page/detail.html', ctx)


@staff_member_required
@permission_required('page.manage_pages')
def page_update(request, pk):
    page = get_object_or_404(Page, pk=pk)
    form = PageForm(request.POST or None, instance=page)
    if form.is_valid() and form.has_changed():
        form.save()
        msg = pgettext_lazy('Dashboard message', 'Saved page')
        messages.success(request, msg)
        return redirect('dashboard:page-details', pk=page.pk)
    ctx = {
        'page': page, 'form': form}
    return TemplateResponse(request, 'dashboard/page/form.html', ctx)


@staff_member_required
@permission_required('page.manage_pages')
def page_delete(request, pk):
    page = get_object_or_404(Page, pk=pk)
    if request.POST:
        menus = get_menus_that_needs_update(page=page)
        page.delete()
        if menus:
            update_menus(menus)
        msg = pgettext_lazy(
            'Dashboard message', 'Removed page %s') % (page.title,)
        messages.success(request, msg)
        return redirect('dashboard:page-list')
    ctx = {'page': page}
    return TemplateResponse(request, 'dashboard/page/modal_delete.html', ctx)

dashboard/settings/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import permission_required
from ..views import staff_member_required
from django.contrib.sites.shortcuts import get_current_site
from django.template.response import TemplateResponse
from core.models import SiteSettings

from .forms import SiteForm, SiteSettingsForm

# Create your views here.

@staff_member_required
@permission_required('core.manage_settings')
def index(request):
    site = get_current_site(request)
    site_settings = site.settings
    print('sssssssssssssss')
    return redirect('dashboard:settings-details', slug=site_settings.slug)


@staff_member_required
@permission_required('core.manage_settings')
def settings_details(request, slug):
    site_settings = get_object_or_404(SiteSettings,slug=slug)
    # Дополнить ключи авторизации
    ctx = {
        'site_settings' : site_settings,
    }
    return render(request, 'dashboard/settings/detail.html', ctx)


@staff_member_required
@permission_required('core.manage_settings')
def settings_edit(request, slug):
    site_settings = get_object_or_404(SiteSettings,slug=slug)
    site_form = SiteForm(request.POST or None, instance=site_settings.site)
    site_settings_form = SiteSettingsForm(request.POST or None, instance=site_settings)
    if request.POST:
        if (site_form.has_changed() and site_form.is_valid()) or (site_settings_form.has_changed() and site_settings_form.is_valid()):
            site_form.save()
            site_settings_form.save()
            return redirect('dashboard:settings-details', slug=site_settings.slug)
    ctx = {
        'site_settings' : site_settings,
        'site_form' : site_form,
        'site_settings_form' : site_settings_form
    }
    return TemplateResponse(request, 'dashboard/settings/form.html', ctx)

dashboard/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import (staff_member_required as _staff_member_required, user_passes_test)

# Create your views here.

def staff_member_required(f):
    return _staff_member_required(f,login_url='account:login')

@staff_member_required
def index(request):
    return render(request,'dashboard/index.html')

dashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
{% load i18n %}
{% load placeholder %}
{% load translate %}

<html lang="{{ LANGUAGE_CODE }}" class="no-js">
<head>
    <title>{% block title %}{{ site.name }}{% endblock %}</title>
    {% block meta %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="generator" content="Saleor">
        <meta name="theme-color" content="#333333">
        <meta name="msapplication-TileColor" content="#2b5797">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="{{ site.name }}">
        <meta name="og:type" content="website">
        {% get_available_languages as LANGUAGES %}
        {% for lang_code, language_name in LANGUAGES %}
            <link rel="alternate" hreflang="{{ lang_code }}"
                  href="{% translate_url url=request.path lang_code=lang_code %}"/>
        {% endfor %}
    {% endblock meta %}

    {% include 'core/favicon.html' %}

    {% block stylesheet %}{% endblock stylesheet %}

    {% block meta_tags %}
        <meta property="og:title" content="{{ site.settings.translated.header_text }}">
        <meta property="og:description" content="{{ site.settings.translated.description }}">
        <meta name="description" content="{{ site.settings.translated.description }}">
        <meta property="og:url" content="{{ request.build_absolute_uri }}">
        <meta property="og:image" content="{% static "images/block1.png" %}">
    {% endblock meta_tags %}


    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body class="{% block body_class %}body-home{% endblock %}">
{% block header %}
    <header>
        <nav class="top-nav" id="top-nav">
            <div class="nav-wrapper">
                <div class="right">
                    <a class="dropdown-button" data-constrainwidth="false" href="#" data-activates="user-action">
                        <svg data-src="{% static "dashboard/images/account-circle.svg" %}" width="24" height="24"
                             fill="#fff"/>
                    </a>
                    <ul id="user-action" class="dropdown-content">
                        <li class="user-name">
                            {{ request.user }}
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{% url 'core:home' %}" target="_blank" class="waves-effect">
                                {% trans "Visit site" context "Dashboard top nav site redirection" %}
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'account:logout' %}" class="waves-effect">
                                {% trans "Log out" context "Log out from account" %}
                            </a>
                        </li>
                    </ul>
                </div>
                <ul class="left">
                    <li>
                        <a href="#" id="toggle-menu">
                            <svg data-src="{% static "dashboard/images/mobile-menu.svg" %}" width="24" height="24"/>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:index' %}" class="logo">
                            <svg data-src="{% static "dashboard/images/logo.svg" %}" height="38px" width="176px"/>
                        </a>
                    </li>

                </ul>
                <ul class="side-nav">
                    <li class="nav-home">
                        <a href="{% url 'dashboard:index' %}">
                            {% trans "Home" context "Dashboard homepage" %}
                        </a>
                    </li>
                    {% if perms.site.manage_settings or perms.shipping.manage_shipping or perms.product.manage_products or perms.page.manage_pages %}
                        <li class="side-nav-section">
                            <p>
                                {% trans "Configuration" context "Dashboard configuration" %}
                            </p>
                            <ul>
                                {% if perms.site.manage_settings %}
                                    <li class="{% block menu_settings_class %}{% endblock %}">
                                        <a href="{% url 'dashboard:settings-index' %}">
                                            {% trans "Site settings" context "Dashboard site settings" %}
                                        </a>
                                    </li>

                                    {% if perms.menu.manage_menus %}
                                        <li class="{% block menu_menus_class %}{% endblock %}">
                                            <a href="{% url 'dashboard:menu-index' %}">
                                                {% trans "Navigation" context "Dashboard menus list" %}
                                            </a>
                                        </li>
                                    {% endif %}

                                    {% if perms.account.manage_users %}
                                        <li class="{% block menu_staff_class %}{% endblock %}">
                                            <a href="{% url 'dashboard:staff-index' %}">
                                                {% trans "Staff" context "Dashboard staff members list" %}
                                            </a>
                                        </li>
                                    {% endif %}

                                    {% if perms.page.manage_pages %}
                                        <li class="{% block menu_product_types_class %}{% endblock %}">
                                            <a href="{% url 'dashboard:product-type-list' %}">
                                                {% trans "Products type" context "Products type list" %}
                                            </a>
                                        </li>
                                    {% endif %}


                                    {% if perms.product.manage_products %}
                                        <li class="{% block menu_products_class %}{% endblock %}">
                                            <a href="{% url 'dashboard:product-list' %}">
                                                {% trans "Products" context "Dashboard products list" %}
                                            </a>
                                        </li>
                                        <li class="{% block menu_categories_class %}{% endblock %}">
                                            <a href="{% url 'dashboard:category-list' %}">
                                                {% trans "Categories" context "Dashboard categories list" %}
                                            </a>
                                        </li>
                                        <li class="{% block menu_pages_class %}{% endblock %}">
                                            <a href="{% url 'dashboard:page-list' %}">
                                                {% trans "Page" context "Dashboard page list" %}
                                            </a>
                                        </li>
                                        <li class="{% block menu_attributes_class %}{% endblock %}">
                                            <a href="{% url 'dashboard:attributes' %}">
                                                {% trans "Attributes" context "Dashboard attributes list" %}
                                            </a>
                                        </li>
                                    {% endif %}

                                {% endif %}
                            </ul>
                        </li>

                        <li class="side-nav-section" id="version-indicator">
                            <p>
                                {% trans "Release:" context "Dashboard software version" %}
                            </p>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
{% endblock %}
{% block top-nav %}
    <div class="subheader top-nav">
        <div class="nav-wrapper container">
            {% block breadcrumbs %}
                <ul class="breadcrumbs">
                    <li class="visible-s">
                        <a href="#">
                            {% trans "Home" context "Dashboard homepage" %}
                        </a>
                    </li>
                </ul>
            {% endblock %}
            {% block header_extra %}{% endblock %}
        </div>
    </div>
{% endblock %}
<main class="main">
    <div class="container">
        {% block content %}{% endblock %}
        <div id="dashboard-app"></div>
    </div>
    <div id="base-modal" class="modal"></div>
    <div id="base-modal-fixed" class="modal modal-fixed-footer"></div>
</main>

{% block footer_scripts %}
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    <script src="{% static "dashboard/js/versatileimagefield.js" %}"></script>
    <script src="{% static "dashboard/js/dashboard.js" %}"></script>
{% endblock footer_scripts %}
{% block custom_js %}{% endblock %}
</body>
</html>

dashboard/templates/dashboard/base_modal.html
{% load i18n %}

<form
  role="form" method="post" action="{% block action_url %}#!{% endblock %}"
  class="{% block form_class %}form-async{% endblock %}" novalidate>
  {% comment %}Empty form_class can be used for non-ajax forms with server redirect.{% endcomment %}
  {% csrf_token %}
  <div class="modal-content">
    <div class="row">
      <div class="col s12">
        <h5>
          {% block title %}{% endblock %}
        </h5>
      </div>
    </div>
    {% if form.non_field_errors %}
      <div class="col 12">
        {% for error in form.non_field_errors %}
          <p class="help-block materialize-red-text">{{ error }}</p>
        {% endfor %}
      </div>
    {% endif %}
    <div class="row">
      {% block content %}{% endblock %}
    </div>
  </div>
  <div class="modal-footer">
    <span class="left">
      {% block actions_left %}{% endblock %}
    </span>
    <a href="#!" class="modal-action modal-close btn-flat waves-effect">
      {% block cancel_action %} {% trans "Cancel" context "Dashboard cancel action" %} {% endblock %}
    </a>
    <button type="submit" class="modal-action btn-flat waves-effect">
      {% block primary_action %}{% endblock %}
    </button>
  </div>
</form>

dashboard/templates/dashboard/base_zero_page.html
<div class="card zero-page">
  <div class="card-content">
    <div class="zero-page__title">
      {% block title %}{% endblock %}
    </div>
    <div class="zero-page__content">{% block content %}{% endblock %}</div>
  </div>
</div>

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static "dashboard/css/versatileimagefield.css" %}">
{% endblock %}